export type GeneratorFn<T> = (args: {
  tokens: string[];
  executeShellCommand: Fig.ExecuteShellCommandFunction;
  generatorContext: Fig.GeneratorContext;
}) => Promise<T> | T;

/**
 * A generator that uses the Fig AI API to generate suggestions.
 *
 * @param prompt The prompt to use for the AI. Can be a string or a generator function.
 * @param message The message to send to the AI. Can be a string or a generator function.
 * @param postProcess A function to post-process the AI's response.
 * @returns A Fig generator.
 */
export function ai({
  prompt,
  message,
  postProcess,
  temperature,
}: {
  prompt?: string | GeneratorFn<string>;
  message: string | GeneratorFn<string>;
  postProcess?: (out: string) => Fig.Suggestion[];
  temperature?: number;
}): Fig.Generator {
  return {
    custom: async (tokens, executeShellCommand, generatorContext) => {
      if (message.length === 0) {
        console.warn("No message provided to AI generator");
        return [];
      }

      const promptString =
        typeof prompt === "function"
          ? await prompt({
              tokens,
              executeShellCommand,
              generatorContext,
            })
          : prompt;

      const messageString =
        typeof message === "function"
          ? await message({
              tokens,
              executeShellCommand,
              generatorContext,
            })
          : message;

      const body = {
        model: "gpt-3.5-turbo",
        messages: [
          ...(promptString
            ? [
                {
                  role: "system",
                  content: promptString,
                },
              ]
            : []),
          {
            role: "user",
            content: messageString,
          },
        ],
        temperature,
      };

      const bodyJson = JSON.stringify(body);
      const escapedBodyJson = bodyJson.replace(/'/g, "'\"'\"'");

      const res = await executeShellCommand(
        `fig _ request --route /ai/chat --method POST --body '${escapedBodyJson}'`
      );

      console.warn(res);
      const json = JSON.parse(res);

      const a =
        json?.choices
          .map((c: any) => c?.message?.content)
          .filter((c: any) => typeof c === "string")
          .map((c: string) =>
            postProcess
              ? postProcess(c)
              : ({
                  icon: "🪄",
                  name: c,
                  insertValue: `'${c}'`,
                  description: "Generated by Fig AI",
                } as Fig.Suggestion)
          ) ?? [];

      return a;
    },
  };
}
