// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    { name: ["--no-sauce"], description: "Remove sauce" },
    {
      name: ["--cheese"],
      description: "cheese flavour",
      args: { name: "flavour", default: "mozzarella" },
    },
    { name: ["--no-cheese"], description: "plain with no cheese" },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
