// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "command",
  description: "Application simple description",
  subcommands: [
    {
      name: "help",
      description: "display help for command",
      priority: 49,
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    { name: ["-V", "--version"], description: "output the version number" },
    { name: ["-f", "--foo"], description: "enable some foo" },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

