// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    {
      name: ["-f", "--float"],
      description: "float argument",
      args: { name: "number" },
    },
    {
      name: ["-i", "--integer"],
      description: "integer argument",
      args: { name: "number" },
    },
    {
      name: ["-v", "--verbose"],
      description: "verbosity that can be increased",
      args: { name: "level", isOptional: true, default: "1" },
    },
    {
      name: ["-c", "--collect"],
      description: "repeatable value",
      args: { name: "value" },
    },
    {
      name: ["-l", "--list"],
      description: "comma separated list",
      args: { name: "items" },
    },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

