// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    { name: ["-v", "--VERSION"], description: "new version message" },
    { name: ["-s", "--sessions"], description: "add session support" },
    {
      name: ["-t", "--template"],
      description: "specify template engine (jade|ejs) [jade]",
      args: { name: "engine", default: "jade" },
    },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

