// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "command",
  subcommands: [
    {
      name: "help",
      description: "display help for command",
      priority: 49,
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    {
      name: ["-n", "--number"],
      description: "specify numbers",
      args: { name: "value", isVariadic: true },
    },
    {
      name: ["-l", "--letter"],
      description: "specify letters",
      args: { name: "value", isOptional: true, isVariadic: true },
    },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

