import { Command, flags } from "@oclif/command";
import { Command as ICommand } from "@oclif/config";
import * as fs from "fs";
import * as prettier from "prettier";

function getArgs(args: ICommand.Arg[]): Fig.Arg[] {
  const figArgs: Fig.Arg[] = [];
  for (const arg of args) {
    if (arg.hidden) continue;
    figArgs.push({
      name: arg.name,
      ...(arg.description && { description: arg.description }),
      ...(arg.default && { default: arg.default }),
      ...(arg.options?.length && { suggestions: arg.options }),
      ...(arg.required === false && { isOptional: true }),
    });
  }
  return figArgs;
}

function getOptions(options: [string, ICommand.Flag][]): Fig.Option[] {
  const figOptions: Fig.Option[] = [];
  for (const [name, flag] of options) {
    if (flag.hidden) continue;
    figOptions.push({
      name: flag.char ? [`-${flag.char}`, `--${name}`] : `--${name}`,
      ...(flag.description && { description: flag.description }),
      ...(flag.type === "option" && {
        args: {
          ...(flag.options?.length && { suggestions: flag.options }),
          ...(flag.default && { default: flag.default }),
        },
      }),
      ...(flag.required === true && { isRequired: true }),
      ...(flag.type === "boolean" && flag.allowNo && { exclusiveOn: [`--no-${name}`] }),
    });
    if (flag.type === "boolean" && flag.allowNo) {
      figOptions.push({
        name: `--no-${name}`,
      });
    }
  }
  return figOptions;
}

function getFigSubcommands(commands: ICommand.Plugin[]): Fig.Subcommand[] {
  const subcommands: Fig.Subcommand[] = [];
  for (const command of commands) {
    // skip this command or hidden commands
    if (command.id === "generateFigSpec" || command.hidden) continue;
    const options: Fig.Option[] = getOptions(Object.entries(command.flags));
    const args: Fig.Arg[] = getArgs(command.args);
    subcommands.push({
      name: command.aliases.length > 0 ? [command.id, ...command.aliases] : command.id,
      ...(command.description && { description: command.description }),
      ...(options.length && { options }),
      ...(args.length && { args }),
    });
  }
  return subcommands;
}

export class GenerateFigSpecCommand extends Command {
  static description = "Generate a Fig completion spec";

  static flags = {
    help: flags.help({ char: "h" }),
    output: flags.string({
      char: "o",
      description: "Output filepath",
    }),
  };

  async run() {
    const { flags: parsedFlags } = this.parse(GenerateFigSpecCommand);

    const spec: Fig.Spec = {
      name: this.config.name,
      subcommands: getFigSubcommands(this.config.commands),
    };

    const template = prettier.format(
      `
      // Autogenerated by @withfig/oclif
  
      const completionSpec: Fig.Spec = ${JSON.stringify(spec)}
  
      export default completionSpec;
    `,
      { parser: "typescript" }
    );
    if (parsedFlags.output) {
      fs.writeFileSync(parsedFlags.output, template);
    } else {
      this.log(template);
    }
  }
}
