// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "command",
  subcommands: [
    {
      name: "help",
      description: "display help for command",
      priority: 49,
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    { name: ["--no-sauce"], description: "Remove sauce" },
    {
      name: ["--cheese"],
      description: "cheese flavour",
      args: { name: "flavour", default: "mozzarella" },
    },
    { name: ["--no-cheese"], description: "plain with no cheese" },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

