// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    {
      name: ["-d", "--drink"],
      description: "drink cup size",
      args: { name: "size", suggestions: ["small", "medium", "large"] },
    },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

