// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "program",
  subcommands: [
    {
      name: "serve",
      options: [
        {
          name: ["-t", "--trace"],
          description: "display extra information when run command",
        },
        {
          name: ["-p", "--port"],
          description: "port number",
          args: { name: "number" },
        },
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "params", isOptional: true, isVariadic: true }],
    },
    {
      name: "build",
      options: [
        {
          name: ["-t", "--trace"],
          description: "display extra information when run command",
        },
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
      args: [{ name: "target" }],
    },
    {
      name: "help",
      description: "display help for command",
      priority: 49,
      args: { name: "command", isOptional: true, template: "help" },
    },
  ],
  options: [
    { name: ["-v", "---verbose"] },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;

