// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
  args: [
    {
      name: "timeout",
      description: "timeout in seconds",
      isOptional: true,
      default: "60",
    },
  ],
};

export default completionSpec;
