// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  description: "example program for argument",
  options: [
    { name: ["-V", "--version"], description: "output the version number" },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
  args: [
    { name: "username", description: "user to login" },
    {
      name: "password",
      description: "password for user, if required",
      isOptional: true,
      default: "no password given",
    },
  ],
};

export default completionSpec;
