// Autogenerated by https://github.com/fedeci/commander-to-fig

const completionSpec: Fig.Spec = {
  name: "",
  subcommands: [
    {
      name: "brew",
      subcommands: [
        {
          name: "tea",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "coffee",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "display help for command",
          priority: 49,
          args: { name: "command", isOptional: true },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "heat",
      subcommands: [
        {
          name: "jug",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "pot",
          options: [
            {
              name: ["-h", "--help"],
              description: "display help for command",
              priority: 49,
            },
          ],
        },
        {
          name: "help",
          description: "display help for command",
          priority: 49,
          args: { name: "command", isOptional: true },
        },
      ],
      options: [
        {
          name: ["-h", "--help"],
          description: "display help for command",
          priority: 49,
        },
      ],
    },
    {
      name: "help",
      description: "display help for command",
      priority: 49,
      args: { name: "command", isOptional: true },
    },
  ],
  options: [
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
