// Autogenerated by @withfig/commander

const completionSpec: Fig.Spec = {
  name: "",
  description: "Application simple description",
  options: [
    { name: ["-V", "--version"], description: "output the version number" },
    { name: ["-f", "--foo"], description: "enable some foo" },
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
};

export default completionSpec;
