// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "command",
  subcommands: [
    {
      name: "child",
      options: [
        { name: ["--gender"], description: "specific gender of child" },
        {
          name: ["-c", "--HELP"],
          description: "custom help message",
          priority: 49,
        },
      ],
    },
    {
      name: "hlp",
      description: "some nice description",
      priority: 49,
      args: { name: "argument", isOptional: true, template: "help" },
    },
  ],
  options: [
    { name: ["-s", "--sessions"], description: "add session support" },
    {
      name: ["-t", "--template"],
      description: "specify template engine (jade|ejs) [jade]",
      args: { name: "engine", default: "jade" },
    },
    {
      name: ["-c", "--HELP"],
      description: "custom help message",
      priority: 49,
    },
  ],
};

export default completionSpec;

