// Autogenerated by @fig/complete-commander

const completionSpec: Fig.Spec = {
  name: "",
  options: [
    {
      name: ["-h", "--help"],
      description: "display help for command",
      priority: 49,
    },
  ],
  args: [{ name: "drink-size", description: "drink cup size" }],
};

export default completionSpec;

